version: "3.9"

services:
  #Brocker
  Broker:
    image: cpabe-dev-image:0.0
    build: ./dockerfiles/Base/
    tty: true
    volumes:
      - ./codes/Broker/:/code
    working_dir: /code
    ports:
      - "1883:1883"
      # - "443:443"
    command: "./RUN.sh "
    # environment:
    networks:
      devnetwork:

  #Proxy
  Proxy:
    image: cpabe-dev-image:0.0
    build: ./dockerfiles/Base/
    tty: true
    volumes:
      - ./codes/Proxy/:/code
    working_dir: /code
    # ports:
    #   - "8080:8080"
    command: "./RUN.sh "
    # environment:
    networks:
      devnetwork:

  #SSL Proxy
  ssl-reverse-proxy:
    image: nginx:1.22
    working_dir: /etc/nginx/conf.d/
    tty: true
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - ./codes/ssl-reverse-proxy/config:/etc/nginx/conf.d/
      - ./codes/ssl-reverse-proxy/ssl:/etc/ssl/custom
    #網路IP設置
    networks:
      - devnetwork

networks:
  devnetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/24
         gateway: 10.1.0.254